Flag to automatically cluster pins & fix to marker moving when clicked
mierzynskim/Xamarin.Forms.GoogleMaps.Clustering pull request #42
Opened 2019-06-11 16:43 UTC by gabrielbunselmeyer

Included in this pull request are the concerns raised on the following issues: #40 and #41.

With a proper explanation and the default being true, I don't think the clustering flag will be too confusing for future users.

Markers moving is a simple fix. Examples are on the relevant issue.

2019-06-14 18:10 UTC, mierzynskim requested changes

2019-06-14 18:10 UTC, mierzynskim commented on src/Xamarin.Forms.GoogleMaps.Clustering/ClusterOptions.cs
> +        public bool AutoClusterAfterAddingPin { get; set; }
I think it should be true by default

2019-06-14 18:10 UTC, mierzynskim commented on src/Xamarin.Forms.GoogleMaps.Android.Utils/Xamarin.Forms.GoogleMaps.Android.Utils.csproj
> -    <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>
why did you change it?

2019-06-14 18:10 UTC, mierzynskim commented on src/Xamarin.Forms.GoogleMaps.Clustering.Android/Xamarin.Forms.GoogleMaps.Clustering.Android.csproj
> -    <AndroidUseLatestPlatformSdk>True</AndroidUseLatestPlatformSdk>
same as above

2019-07-15 13:27 UTC, mateuswolkmer commented
@mierzynskim, @gabrielbunselmeyer used to work in my project and he left the company recently, so I believe he won't carry on with the pull request, but the changes are still relevant to us. Can you implement the requested changes or should I make a new pull request with the same changes?

2019-07-24 19:58 UTC, mierzynskim commented
@mateuswolkmer You can create a new PR. I would prefer if you change this PR but I think you would need access to your co-worker's fork repo.

2019-07-26 11:22 UTC, mateuswolkmer commented
@mierzynskim I'm with a lot of work in other projects but I'll see if I can do something about it in the following days.

2020-04-13 16:45 UTC, closed without merging